### ISSUE TITLE
Plugin breaks brimhaven agility

### ISSUE THREAD

**Issue by theIsaia** [Chris-Bitler/Runelite-StealingArtefacts#3]
This plugin currently seems to cause the brimhaven agility dungeon indicator arrow to break (found out via trial and error turning plugins on and off). A runelite dev suggested that its probably caused by however this plugin uses the hint arrow, might be worth looking into if you are still willing to update the plguin. If not hopefully others who experience this issue see's this and turns off the plugin when doing brimhaven agility!

**Comment by mattantonelli** [comment]
I ran into the same issue on my client. Disabling this plugin resolved the issue.

**Comment by Chris-Bitler** [comment]
Should be fixed, posting new update to plugin hub so it should be available soon hopefully
