### ISSUE TITLE
NullPointerException - onGameObjectDespawned

### ISSUE THREAD

**Issue by pwatts6060** [Chris-Bitler/Runelite-StealingArtefacts#8]
`java.lang.NullPointerException: Cannot invoke "net.runelite.api.GameObject.getId()" because "this.markedObject" is null
	at io.cbitler.stealingartefacts.StealingArtefactsPlugin.onGameObjectDespawned(StealingArtefactsPlugin.java:176)`
Shooting star object despawned and spat this error in console

**Comment by Chris-Bitler** [comment]
Should be fixed once https://github.com/runelite/plugin-hub/pull/3066 is merged
